[project]
name = "quality-challenge"
version = "0.1.0"
description = "An async web crawler with configurable filtering and scoring"
authors = [
    {name = "Simona Lihosithova",email = "simona.lihosithova@faculty.ai"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "~3.11.9"
dependencies = [
    "polars (==1.25.*)",
    "jupyter (>=1.1.1,<2.0.0)",
    "crawl4ai (==0.5.0.post4)",
    "sentence-transformers (>=4.0.1,<5.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "langchain (>=0.3.22,<0.4.0)"
]

[tool.poetry]
packages = [
{ include = "data_quality_utils", from = "src" }
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"
black = "^25.1.0"
pre-commit = "^4.2.0"
nbqa = "^1.9.1"
isort = "^6.0.1"
flake8 = "^7.2.0"
pyupgrade = "^3.19.1"
pdfminer-six = "^20250327"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
